### ISSUE TITLE
如何让cmd bat自动获取管理员权限

### ISSUE THREAD

**Issue by wkgcass** [wkgcass/public-chat#23]
如何在cmd的bat脚本中，自动以管理员权限的模式启动其他程序？

**Comment by wkgcass** [comment]
改动：我运行的是一个bat脚本，我把第一个""去掉就正常了，否则会有一个空的终端跳出来

**Comment by mhiau** [comment]
請教是否缺少一個 "app.bat" 檔案，無法執行 "launch.bat" 或 "launch-with-pwsh.bat"？

想執行的程式是台港澳躍遷服，不知是否還需要幻塔測試服啟動器？我並不知道這個壓縮檔是從哪生出來的
hotta-multi-instances-launcher.zip
